### PR TITLE
here is my take  on it...does this make sense?

### PR DESCRIPTION
**Pull request by falkonprods**

### CODE REVIEW

**Comment by falkonprods** [comment]
layer3 drew

**Review by cryptopanter — CHANGES_REQUESTED** [review]
I think Member and Dao voting member are vague!..Conflict of permissions

**Comment by falkonprods** [comment]
> I think Member and Dao voting member are vague!..Conflict of permissions (@cryptopanter)

I think there is (1) a mistake in the graphic - it says "vote" for standard members, but (2) I don't understand what is vague - voting members are members who get to partake in governance and spending.  In some DAOs, every member could be a voting member. In others, there will be members who are allowed in the DAO and can contribute to the DAO, but won't be allowed  to vote until they have proven themselves. I think this is a  great mechanism for management because it allows for inclusion (non-voting members can create proposals and execute on them), but you need to be promoted to voting member. If every member is given a vote, or allowed to stake, you can have unknowns  come in and change the nature of the DAO, or  freeloaders who never vote, never contribute and become a drag on the system. With this simple methodology, active participants are rewarded with voting rights that can be attached to a token and then be able  to contribute. Voting  members can nominate and elect new voting members by consensus, likewise, they can  demote voting  members to non-voting members by consensus.  To me this is simple but effective.

**Comment by JMKJR** [comment]
Cool. Before I ask further questions, is the following an accurate description of daoOS as you see it? @falkonprods 

"An RBAC platform for managing funded proposals".

**Comment by falkonprods** [comment]
> Cool. Before I ask further questions, is the following an accurate description of daoOS as you see it? @falkonprods
> 
> "An RBAC platform for managing funded proposals".

No. There isn't even RBAC other than voting/non-voting.

daoOS is a DAO Management System, starting with a methodology for funding proposals/projects and moving into governance.

**Comment by cryptopanter** [comment]
> > I think Member and Dao voting member are vague!..Conflict of permissions (@cryptopanter)
> 
> I think there is (1) a mistake in the graphic - it says "vote" for standard members, but (2) I don't understand what is vague - voting members are members who get to partake in governance and spending. In some DAOs, every member could be a voting member. In others, there will be members who are allowed in the DAO and can contribute to the DAO, but won't be allowed to vote until they have proven themselves. I think this is a great mechanism for management because it allows for inclusion (non-voting members can create proposals and execute on them), but you need to be promoted to voting member. If every member is given a vote, or allowed to stake, you can have unknowns come in and change the nature of the DAO, or freeloaders who never vote, never contribute and become a drag on the system. With this simple methodology, active participants are rewarded with voting rights that can be attached to a token and then be able to contribute. Voting members can nominate and elect new voting members by consensus, likewise, they can demote voting members to non-voting members by consensus. To me this is simple but effective.
> 
> Also: Voting members can do anything members can do, but also have voting/consensus powers for governance of the DAO.

Ok.. Now what is the problem with this? Answer: centralization!.. If voting members should chose who to vote or not that's agianst the decentralization essence!... I see your concern about preventing many unknown and uncommitted participants to arrive and disturb the balance in voting but there s a solution for that: we can give voting allowance to all members that hold and lock Stx for the proposal. Thisway, you make sure, all participants are real stx holders and care about their investments. In addition, it's done in decentralized way where there is no one needed to approve your permission to vote!

**Comment by falkonprods** [comment]
> Ok.. Now what is the problem with this? Answer: centralization!.. If voting members should choose who to vote or not that's against the decentralization essence!... I see your concern about preventing many unknown and uncommitted participants to arrive and disturb the balance in voting but there s a solution for that: we can give voting allowance to all members that hold and lock Stx for the proposal. This  way, you make sure, all participants are real stx holders and care about their investments. In addition, it's done in decentralized way where there is no one needed to approve your permission to vote!

I completely disagree. Decentralization does not necessarily mean everyone gets a vote. Decentralization means simply that the decisions of an organization are distributed in nature and not decided through a traditional, hierarchical political or corporate structure. There are different types of decentralization - one of which is "fully open" decentralization, which is I believe what you are referring to, where anyone is allowed to enter the organization and participate in decision-making. Many DAOS are not, in fact, open. The reason is that empowering anyone to join a DAO and vote based on tokens can lead to an organization controlled by those with the most money. Another reason is that empowering anyone to have governance control over the DAO could allow for the DAO and it's funds to be compromised - all it takes is a group of people greater than the current number of members to coordinate a takeover. In smaller DAOs with a treasury this is no small risk. Having some kind of consensus-based methodology to choose members is still decentralized.

Take Stacks Foundation - they are decentralized, but not everyone gets to participate in the governance of it. You get elected to the foundation, and through that process are able to then vote on governance initiatives. As non-governing participants in the Stacks ecosystem, we are still open to apply for Stacks grants - I don't see how this is ANY different from what we are doing. The difference is that under daoOS we would be members of the DAO. Will anyone be allowed into Syvita and given full voting rights?  I'm going to guess probably not - there needs to be some level of participation that precludes membership.

If you make everyone a voting member, this leaves two options:  one where anyone can enter and vote based on their funding 
 power, which will create an organization controlled by the funders. The other would essentially just be a HIGHER  BAR for entry into the DAO by enabling everyone to vote and give consensus on new (voting) members. I feel that the current methodology - with voting and non-voting members  - allows a DAO to be more inclusive because it gives people the opportunity to contribute to the DAO and prove themselves so that they can eventually be elected to a voting member position.

This  all  having been said, I think daoOS should be flexible in it's implementation - if a DAO wants  to enable all members to vote: great! If it wants to enable people to elect voting members: great! If it wants to empower people to become voting members through  token acquisition: great! I don't think daoOS  should be opinionated in any way, but rather flexible to adapt to as many different types of organizations as could possibly adopt it.

**Review by cryptopanter — APPROVED** [review]

**Comment by cryptopanter** [comment]
Ok i am convinced and did approve... Just to review: for example, Syvita team deploy DAO contract for raising fund on its projects.. Now the deployer, Syvita member, should define the first voting members in the beginning?.. I mean should deployer has the power to select the initial boarding members?

**Comment by LNow** [comment]
> Now the deployer, Syvita member, should define the first voting members in the beginning?.. I mean should deployer has the power to select the initial boarding members?

We can define them inside the contract, so that when it will be deployed they'll be set immediately.

**Comment by asteriabtc** [comment]
> Ok i am convinced and did approve... Just to review: for example, Syvita team deploy DAO contract for raising fund on its projects.. Now the deployer, Syvita member, should define the first voting members in the beginning?.. I mean should deployer has the power to select the initial boarding members?

yeah [syvita's kernel](https://github.com/syvita/dao) will work this way. we'll define all the current members hardcoded into the contract, and require new members to be voted in using a certain type of proposal designed to accept new members to the Guild.

**Review by asteriabtc — APPROVED** [review]

**Review by LNow — APPROVED** [review]

**Review by JMKJR — APPROVED** [review]
If this is the model that works for Freehold/Stacks Foundation then let's do it.

**Pull request merged**
