### PR TITLE
Add files via upload for architecture drawings 

### PR DESCRIPTION
**Pull request by cryptopanter**
Hello guys...
I have been working on @LNow drawing drafted architecture (DAO.drawio) and tried to separate each layer as per Labs3 standard C4model... The output format is drawio and can be opened in Draw.io online platform. I also added the images of the drawing for each layer(PNG pic). Therefore, the derived drawings could be more easily understandable for all members to catch the whole idea structure and follow up in better way.

### CODE REVIEW

**Review by LNow — APPROVED** [review]

**Comment by 314159265359879** [comment]
@cryptopanter very nice you put this together. I will go through these, one diagram at a time. Here is my feedback on the first one. I did not want to work in the drawio file so you can easily review my comments I just put them in the image. 

daoos_DAO-1 2-layer1

**Comment by 314159265359879** [comment]
here it is for layer two, sorry for all the unfriendly red, all meant in the best way ofc, I think these will be very helpful to explain to others what we are doing. 
daoos_DAO-1 2-layer2-feedback

**Comment by 314159265359879** [comment]
For the next layer (3) we would have a diagram per container in layer 2. You made the DAO core Contract diagram, and are showing people atop. That should only be the "UI" see example:
image

**Comment by cryptopanter** [comment]
> @cryptopanter very nice you put this together. I will go through these, one diagram at a time. Here is my feedback on the first one. I did not want to work in the drawio file so everyone can easily review my comments I just put them in the image.
> 
> daoos_DAO-1 2-layer1

So i think we go for DAO without "the", ok?
Also you are right about the distinction of administrator and owner, i will correct that. 
Btw, i agree with you about Members. They can only vote and view DAO contract and it's deployer than can create proposal, you agree?

**Comment by cryptopanter** [comment]
> here it is for layer two, sorry for all the unfriendly red, all meant in the best way ofc, I think these will be very helpful to explain to others what we are doing.
> daoos_DAO-1 2-layer2-feedback

Thanks very much for your in-depth feedback... What if we omit the term "core" snd generalhy say "DAO Contract"?.. So this way both core contract and optional ones can be included

**Comment by cryptopanter** [comment]
> For the next layer (3) we would have a diagram per container in layer 2. You made the DAO core Contract diagram, and are showing people atop. That should only be the "UI" see example:
> image

So you suggest to use zoom-in method in visualization?.. If so, then how many output picture should we take from on layer3 drawing?.... The more wider and in-detail it is, the less image quality we'll have at the enf!

**Comment by LNow** [comment]
> For the next layer (3) we would have a diagram per container in layer 2. You made the DAO core Contract diagram, and are showing people atop.

I wouldn't consider this as a mistake or a flaw. 
Indeed according to C4 modeling technique, 3rd level should not have any actors or users, but adding it is not a big thing. I've done it in the past multiple times. It is useful at the beginning of your journey with C4 and when you have multiple containers used/exposed to different users, and you don't want to jump back and forth between 2nd and 3rd level diagrams to check who will use what.

**Review by pxydn — CHANGES_REQUESTED** [review]
Regarding [this one](https://github.com/labs3/daoOS/pull/28#issuecomment-829937631), I agree with what @314159265359879 said. Worth saying that the contract gives no priority to the deployer of the contract, as they cannot destroy the DAO (contract). anyone can deploy a DAO. it shouldn't make them the owner, that takes away the very meaning of 'D'AO. 

for [layer 2](https://github.com/labs3/daoOS/pull/28#issuecomment-829962388), Next.js is a React framework and doesn't work with others which resolves that. I could also create a contract that acts as a sort of registry for a landing page/explorer of all known DAOs using the set protocol (which would be implemented as a SIP eventually). That would solve that. On the DAO core contracts bit, yes, I agree that we should name that to DAO Contract. I have an idea for this, will explain in the channel and follow up here.

**Comment by 314159265359879** [comment]
> Btw, i agree with you about Members. They can only vote and view DAO contract and it's deployer that can create proposal, you agree?

@cryptopanter no this is not what I meant. The deployer only plays a role at the start, and he may appoint the first member(s) with admin priveleges but the deployer as @pxydn said is just that and should not have any lasting privileges after the DAO is launched. 

I compare this with registering a namespace. After registration you need to launch it, after the launch anyone can register names on it. With the DAO anyone can start a DAO, after deploying it (comparable to Launching a namespace) anyone can use it. 
During deployment that means atleast one member/admin has to be appointed. 

What I meant to say with
1. and 2. is that from member there should be two arrows to the "_DAO block_" because the intent between the two options is different, a single arrow will not suffice. 
arrow 1. Making proposals1 will also require an other piece of software
then arrow 2. Voting on proposals. I do not think it is a problem if every member can make proposals, shit proposals won't get any votes and can't hurt ;-) the selection process is the point in the first place of course or we won't know what the good proposals are.

**Comment by 314159265359879** [comment]
> Thanks very much for your in-depth feedback... What if we omit the term "core" snd generalhy say "DAO Contract"?.. So this way both core contract and optional ones can be included

That could work too. Perhaps "DAO Contract**s**" there will surely be several which can be elaborated on in the next level? I guess it depends how much information you want to give at this level. 

I thought it might be helpful to split them up here. Because in the description we can put the core contracts and optional contracts if we split that up here and we know future DAO's will always use the core contracts = mandatory architecture. While the optional contracts used will vary widely, meaning level 3 will only be changed for that part. Core contract and interface will mostly remain the same.

**Comment by 314159265359879** [comment]
> 
> 
> > For the next layer (3) we would have a diagram per container in layer 2. You made the DAO core Contract diagram, and are showing people atop.
> 
> I wouldn't consider this as a mistake or a flaw.
> Indeed according to C4 modeling technique, 3rd level should not have any actors or users, but adding them is not a big thing. I've done it in the past multiple times. It is useful at the beginning of your journey with C4 and when you have multiple containers used/exposed to different users, and you don't want to jump back and forth between 2nd and 3rd level diagrams to check who will use what.

Ah I agree, showing the interaction so you don't have to go back is excellent. Going over this again I see I misread the diagram. Because the UI is zoomed in together with the DAO (core) contracts component. Having them all on the same canvas is very nice really.

**Review by 314159265359879 — CHANGES_REQUESTED** [review]
see comments for diagram 1 and 2.

**Comment by cryptopanter** [comment]
> @cryptopanter very nice you put this together. I will go through these, one diagram at a time. Here is my feedback on the first one. I did not want to work in the drawio file so everyone can easily review my comments I just put them in the image.
> 
> daoos_DAO-1 2-layer1

I think I keep System in "DAO system"...and also the short description of used tech as "Stacks Smart Contract"...no need to explain the concept of DAO here. We need the diagram to be as concise as possible. There is Wiki to learn more about each part of the architecture and the whole concept of DAO.

**Comment by cryptopanter** [comment]
> Regarding [this one](https://github.com/labs3/daoOS/pull/28#issuecomment-829937631), I agree with what @314159265359879 said. Worth saying that the contract gives no priority to the deployer of the contract, as they cannot destroy the DAO (contract). anyone can deploy a DAO. it shouldn't make them the owner, that takes away the very meaning of 'D'AO.
> 
> for [layer 2](https://github.com/labs3/daoOS/pull/28#issuecomment-829962388), Next.js is a React framework and doesn't work with others which resolves that. I could also create a contract that acts as a sort of registry for a landing page/explorer of all known DAOs using the set protocol (which would be implemented as a SIP eventually). That would solve that. On the DAO core contracts bit, yes, I agree that we should name that to DAO Contract. I have an idea for this, will explain in the channel and follow up here.
> 
> ^^ I have an idea for versioning DAOs. when it wants to add additional features or contracts, etc. The DAO would be contained within a single contract, but could have new versions of the contract voted upon and then implemented with a majority vote.

So for UI, you suggest removing Next.js or replacing it with sth?

**Comment by cryptopanter** [comment]
> here it is for layer two, sorry for all the unfriendly red, all meant in the best way ofc, I think these will be very helpful to explain to others what we are doing.
> daoos_DAO-1 2-layer2-feedback

For public users, how they view the proposals and votes?...I think they should read contract transactions to see the data and as such it's some kinda interaction

**Comment by cryptopanter** [comment]
> > For the next layer (3) we would have a diagram per container in layer 2. You made the DAO core Contract diagram, and are showing people atop. That should only be the "UI" see example:
> > image
> 
> So you suggest to use zoom-in method in visualization?.. If so, then how many output picture should we take from on layer3 drawing?.... The more wider and in-detail it is, the less image quality we'll have at the end!

ok I didn't know that...but i still suggest to keep person/members blocks in 3rd layer to make it easy and more understandable for newcomers

**Comment by cryptopanter** [comment]
> Regarding [this one](https://github.com/labs3/daoOS/pull/28#issuecomment-829937631), I agree with what @314159265359879 said. Worth saying that the contract gives no priority to the deployer of the contract, as they cannot destroy the DAO (contract). anyone can deploy a DAO. it shouldn't make them the owner, that takes away the very meaning of 'D'AO.
> 
> for [layer 2](https://github.com/labs3/daoOS/pull/28#issuecomment-829962388), Next.js is a React framework and doesn't work with others which resolves that. I could also create a contract that acts as a sort of registry for a landing page/explorer of all known DAOs using the set protocol (which would be implemented as a SIP eventually). That would solve that. On the DAO core contracts bit, yes, I agree that we should name that to DAO Contract. I have an idea for this, will explain in the channel and follow up here.
> 
> ^^ I have an idea for versioning DAOs. when it wants to add additional features or contracts, etc. The DAO would be contained within a single contract, but could have new versions of the contract voted upon and then implemented with a majority vote.

This is only the 2nd version of architectural drawing, version 1.2. In the next version we can have more matured and completed diagrams....I think it's good to keep the project advancement in version numbering so even later on we can roll back to primary diagrams and use them or choose them to show which one to which audience.

**Review by 314159265359879 — APPROVED** [review]

**Review by pxydn — APPROVED** [review]

**Pull request merged**
