### PR TITLE
Added typescript compiler github action, fixed prettier github action

### PR DESCRIPTION
**Pull request by JMKJR**

### CODE REVIEW

**Comment by cryptopanter** [comment]
Typescript is good for correction of the output codes in Javascript right? Which parts we ll use Javascript?

**Comment by asteriabtc** [comment]
> Typescript is good for correction of the output codes in Javascript right? Which parts we ll use Javascript?

we should be using typescript over javascript. typescript is much better than js and all js is instantly compatible when you run it in typescript.

**Comment by JMKJR** [comment]
I prematurely added assignees to this draft, sorry if i've spammed your notifications.

Adding these github actions doesn't work out of box for us due to our monorepo structure. I'm testing different ways of fixing that. Will revisit after returning from Miami.

**Comment by cryptopanter** [comment]
> I prematurely added assignees to this draft, sorry if i've spammed your notifications.
> 
> Adding these github actions doesn't work out of box for us due to our monorepo structure. I'm testing different ways of fixing that. Will revisit after returning from Miami.

Oh then cheers! 🍹Have a good time in Miami... After returning elaborate more on this PR and typescript and why monorepo structure 🎩

**Comment by JMKJR** [comment]
> Oh then cheers! 🍹Have a good time in Miami... After returning elaborate more on this PR and typescript and why monorepo structure 🎩

Thanks! Sure thing:
1. Typescript - Static typing (that plain javascript lacks by default) makes our code easier to read and understand. This github action will enforce strictness of this so we are held to a certain code quality standard.
2. Monorepo - Our frontend and smart contracts are related but separate projects. The monorepo structure allows us to keep both in the same repository for easy reference and editing but maintains them as separate standalone packages.

**Comment by JMKJR** [comment]
Summary of changes:
* `Prettier` is configured both at the root level and in the subdirectory level but is run from root using the `lint` github action. Specifying a subdirectory to run `prettier` from in the github action did not work for me, so that's why it's installed in root as well. If you wish to lint locally, please run the `prettier` commands from the root directory since that's what our github action will do.
* Typescript is configured **only at the root level**. I tried using the `--project` parameter as advertised in [docs](https://github.com/marketplace/actions/typescript-compiler) but it didn't work for me. If anyone is feeling adventurous you can have a go at that. However, I don't see the lack of Typescript in our `packages/` as an issue anyways since they are dev dependencies and they don't get included in a build even if they were there. So just run `npx tsc` from root.
* There is an error in our `tsc` action about `@blockstack/clarity`. I originally thought this was due to lack of `types` for the module but when I ran `npm test` the contracts tests are failing due to something with this package. I checked out `main` and the tests are failing on `main` too. So I'm choosing to ignore this error for now since I don't think this branch is to blame. This can be investigated further after merge.
* We didn't have `package-lock.json` added in main. This branch adds it.
* `node_modules` was not ignored in our `.gitignore`, this branch adds it.

**Comment by JMKJR** [comment]
@asteriabtc @cryptopanter Please do not merge after approval, I'd like to "squash and merge" to condense changes down to 1 commit for cleanliness.

**Comment by LNow** [comment]
I removed myself from reviewers and assigners lists as this PR is out of scope of my field of expertise and I won't be able to provide any meaningful feedback.

**Review by asteriabtc — APPROVED** [review]

**Pull request merged**
