### PR TITLE
Members list UI

### PR DESCRIPTION
**Pull request by JMKJR**
Summary of changes:
* Rough draft of what the members page could look like. Using hardcoded data.
* This branch also includes navbar fixes for issues that became apparent when content was added.

Please test responsiveness and provide design feedback/suggestions.

### CODE REVIEW

**Comment by 314159265359879** [comment]
@SyAsteria can you fix the cloudflare pages deployment, that was very helpful on #56 too, It really helps me test this on multiple platforms fast.

**Review by 314159265359879 — APPROVED** [review]
Looks impressive. It is looking and responding the same way on Firefox, Brave, Chrome on windows and similarly with Firefox and Safari on iOS.

I think the shadow under the button is no improvement. Because of the sharp corners at the top it looks like one part with the grey square. It may look better to elevate the whole square (Voting members and non-voting members).

A minor when scrolling and pulling the up when there is nothing left the shadow has a sharp edge (1):
image

I still think the title "Voting Members" should stand out more. Larger font perhaps, and/or a line (1-3 px) under, or dark (hamburger menu or purple maybe) background the size of the purple button at the bottom are some options in my view. 
image


image

image
Or the simplest:
image

**Comment by 314159265359879** [comment]
noticed something strange after all. When I load the page the first time I see a shadow dropped under the button, after a reload (F5) there is no longer a shadow that drops. This does not happen on iOS, Safari ++. Firefox/iOS it looks like the css is not applied right away showing text (title/members/button) in another font for a brief moment (maybe just the staging area). Shadow remains in iOS though.

**Comment by 314159265359879** [comment]
In this flow on mobile:
a. I click the hamburger menu
b. Menu opens
c. I click Members (shadow = yes)
Menu is still covering the screen, want to collapse it with (c.)?

**Comment by JMKJR** [comment]
@314159265359879 A+ testing as always, thanks so much!

> I think the shadow under the button is no improvement. Because of the sharp corners at the top it looks like one part with the grey square. It may look better to elevate the whole square (Voting members and non-voting members).

I'll try elevating both and you can sample that. Maybe we don't need any elevation at all? My initial thinking was to try to get the button to have more of a contrast from the rest of the List component so it looks more like a clickable button than if it were just blended into the list. Maybe the solution is not elevation, but changing something with the button border? We can test different approaches until we get it right :)

> A minor when scrolling and pulling the up when there is nothing left the shadow has a sharp edge (1):

Yeah this is observant. I could try adding some margin to the bottom so there is more white space and a smoother transition on page overscroll.

> I still think the title "Voting Members" should stand out more. Larger font perhaps, and/or a line (1-3 px) under, or dark (hamburger menu or purple maybe) background the size of the purple button at the bottom are some options in my view.

What if we just try some purple text here?

> noticed something strange after all. When I load the page the first time (click members) I see a shadow dropped under the button, after a reload (F5) there is no longer a shadow that drops (Windows:Edge/Firefox/Brave/Chrome). This does not happen on iOS, Safari ++. Firefox/iOS it looks like the css is not applied right away showing text (title/members/button) in another font for a brief moment (maybe just the staging area). Shadow remains in iOS though.

Another astute observation! I just investigated this and it looks like it's an issue with the `boxShadow` css class I'm using from `material-ui`. If I just use the `box-shadow` css property instead to accomplish the same thing, then the shadow remains intact on refresh. As for the temporary flash of default fonts, it looks like this only happens very briefly on initial render or refresh while the browser is loading those fonts. It seems there's nothing I can do about that as the alternatives and mitigation strategies are less preferable.

> In this flow on mobile:
a. I click the hamburger menu
b. Menu opens
c. I click Members
Menu is still covering the screen, want to collapse it with (c.)?

Yes! good catch.

**Comment by 314159265359879** [comment]
> I'll try elevating both and you can sample that. Maybe we don't need any elevation at all? My initial thinking was to try to get the button to have more of a contrast from the rest of the List component so it looks more like a clickable button than if it were just blended into the list. Maybe the solution is not elevation, but changing something with the button border? We can test different approaches until we get it right :)

> > A minor when scrolling and pulling the up when there is nothing left the shadow has a sharp edge (1):
> 
> Yeah this is observant. I could try adding some margin to the bottom so there is more white space and a smoother transition on page overscroll.

Perhaps no shadow would also be just fine. solves this problem too and I think it may be clear enough that it is a button and what it does because of the location and the text "show more"? I guess it is good to get some more input on this from the others. Want to show them without shadow, see what they think?

> What if we just try some purple text here?

Yes lets do that, bold too?

**Comment by JMKJR** [comment]
@314159265359879 summary of latest commit:
* Added close drawer after tapping link on mobile.
* Removed shadow/elevation around Show More button.
* Made subheader text of MemberGroup component bigger, bold, and purple.
* Increased margin between MemberGroup components.

**Comment by 314159265359879** [comment]
Looks awesome now! Looking forward to the next one 😀

**Pull request closed without merging**
