### PR TITLE
Create CODE_OF_CONDUCT.md

### PR DESCRIPTION
**Pull request by Zk2u**

### CODE REVIEW

**Comment by 314159265359879** [comment]
Joberding did a lot of work on the _code of conduct_ and _code of enforcement_ for Stacks, I think we would be wise to borrow from it for daoOS. And it makes sense to align it with the Stacks code right?

https://github.com/stacksgov/pm/issues/132#issuecomment-787923297

**Comment by pxydn** [comment]
@314159265359879 this is an awesome point and that's a good start. though i'm not too keen on the whole professional setting part. i'd want to rework that.

**Comment by asma-rana** [comment]
Thank you for compiling this excellent Code of Conduct letter.  I pledge to treat others as we wish to be treated. I ensure to comply with set standards to act and interact in ways that contribute to an open, welcoming, diverse, inclusive, and healthy community.

**Comment by 314159265359879** [comment]
I think this is ready for a review. We can always work on it later but it should clutter up the pull request section anymore ;-)

**Review by 314159265359879 — APPROVED** [review]

**Pull request closed without merging**
